### ISSUE TITLE
add to ramdajs.com

### ISSUE THREAD

**Issue by buzzdecafe** [davidchase/ramtuary#11]
this repl is great and i'd love to replace existing ramdajs.com/repl with it. do you have any objection to that?

**Comment by davidchase** [comment]
@buzzdecafe thanks and I do not have an objections to that, i actually was thinking about opening a PR to do just that I was thinking about cleaning it up a bit before submitting a PR (didnt get the chance just yet to do so) and I had an idea for displaying examples in a offscreen menu... something like [this](http://tympanus.net/Development/MultiLevelPushMenu/index2.html)

**Comment by buzzdecafe** [comment]
very nice! ok, i will keep an eye out for the PR.
