### ISSUE TITLE
Futures example broken

### ISSUE THREAD

**Issue by dalgard** [davidchase/ramtuary#12]
The url in the _Futures_ example seems to be broken.

Also, I believe the `::` bind syntax allows for the first part to be omitted, if it is equal to the base of the second part:

`console::console.log` ≡ `::console.log`

This syntax is also shown in the first few lines of README.md.

**Comment by davidchase** [comment]
thanks for the heads up i will resolve the broken link... been working on a new version with rollup + [buble](https://gitlab.com/Rich-Harris/buble) for the compiling

**Comment by davidchase** [comment]
thanks again should be working now https://goo.gl/U1cO4f
