### ISSUE TITLE
sanctuary@0.14.x

### ISSUE THREAD

**Issue by davidchambers** [davidchase/ramtuary#17]
Could we update to the latest Sanctuary release?

**Comment by davidchase** [comment]
Sure thing gimme a bit once I have access to my computer 😁

**Comment by davidchase** [comment]
done https://github.com/davidchase/ramtuary/commit/c0ecf7f254e814bc6edbe0732eedff347a3f1cd0

**Comment by davidchambers** [comment]
:tada:
