### ISSUE TITLE
Look for alternative to Wzrd.in

### ISSUE THREAD

**Issue by davidchase** [davidchase/ramtuary#19]
ref #18

**Comment by davidchase** [comment]
maybe use unpkg? ref also #20

**Comment by Shard** [comment]
Just tried to use the repl and wzrd.in seems to be down again :(

unpkg works pretty well, used by alot of sites and have not seen it go down yet myself.

**Comment by davidchase** [comment]
I will try again with unpkg

**Comment by davidchase** [comment]
hmm it seems like https://unpkg.com/sanctuary@0.15.0/ only provides the source code and no dist bundles or umd which i believe we need in order to get all of the dependencies in the correct order and it seems like sanctuary has a few :(

@Shard any thoughts?

**Comment by davidchase** [comment]
for the mean time i just downloaded the deps to the repo and pulling from there. curious to know your thoughts about `unpkg` still 😄

**Comment by davidchambers** [comment]
> i believe we need in order to get all of the dependencies in the correct order and it seems like sanctuary has a few

See [installation][1] if you decide to add Sanctuary's dependencies manually. :)


[1]: https://sanctuary.js.org/#installation

**Comment by davidchase** [comment]
@davidchambers thanks for the tips as usual 😁I will give that a try

**Comment by davidchase** [comment]
updated to unkpg for all except for tcomb thanks again ! 👍
