### ISSUE TITLE
Update deps ?

### ISSUE THREAD

**Issue by danielo515** [davidchase/ramtuary#20]
Hello,

Your project looks awesome. Any chance to update it to use the latest sanctuary version ?

Regards

**Comment by davidchase** [comment]
thanks, and sure thing 👍

**Comment by danielo515** [comment]
Hello @davidchase 
Thank you for your prompt commit. I am a bit confused about how your REPL works. I saw that you just added the latest sanctuary version to the list of imported libraries by a script tag. But looking at your rollup configuration seems that what you are actually using is the npm installed version. Also I noticed that your main branch are gh-pages, which is usually the publish branch, but it looks more like a dev branch, and the master branch, which is usually the dev-branch looks like a gh-pages branch. Could you please clarify how does it work exactly ?
I was planning to fork your REPL and add a couple of extra libraries for a FP REPL instead of just a sanctuary + ranmda repl (basically lenses and futures).

Thanks in advance.

**Comment by davidchase** [comment]
@danielo515 hi so this repl was originally a fork/experiment from the original [ramda repl](https://github.com/ramda/repl) before it got a face lift, so basically i forked their repl made some changes and merge mine back with theirs minus a few libraries.

Its been a while... but iirc, the index.html script tags are specifically for the REPL when the user types code, while the package.json dependencies are for the code that scripts the repl. For example i provide TComb for the repl users but dont use it to build the repl itself. Now there are probably better ways of doing this to avoid the redundancies but i hacked this together pretty quickly and after it got merged back into the ramda repl i didnt think anyone still used ramtuary as much nor did i have time to come back and refactor the code.

>  Also I noticed that your main branch are gh-pages, which is usually the publish branch, but it looks more like a dev branch, and the master branch, which is usually the dev-branch looks like a gh-pages branch

i use gh-pages branch for the site as place to host it so its the master/dev one... the other branches on here were just experiments and probably can be culled.

maybe you can fork the ramda repl and add those lenses and futures, etc libs to that one...

hope this answers your questions.. let me know

**Comment by danielo515** [comment]
Thank you very much for clarification @davidchase

**Comment by davidchase** [comment]
@danielo515 yah for sure :smile: if you ever end building a repl or something let me know it would be cool to see :100:
